### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Candice-Louw**
@asohh @nliakm @fhauptmann @TomHutter @vidi42 @sabpet @FredrikSchaeferVitagroup @kadeng @nk-designz @kiney @tbroyer @ulf1 @robbmue @hzi-old are contributors to this repository.

In order to add the GPLv3 license, please indicate in a comment that you agree to put everything you contributed under GPLv3:
I [@ yourusername] agree to put all my contributions to SORMAS-Docker under GPLv3 license.

Once this is completed, the pull request could be converted, merged and the license added to the repository.

### CODE REVIEW

**Comment by nk-designz** [comment]
I @nk-designz agree to put all my contributions to SORMAS-Docker under GPLv3 license. :)

**Comment by tbroyer** [comment]
I @tbroyer agree to put all my contributions to SORMAS-Docker under GPLv3 license.

**Comment by kiney** [comment]
I @kiney  agree to put all my contributions to SORMAS-Docker under GPLv3 license.

**Comment by FredrikSchaeferVitagroup** [comment]
I @FredrikSchaeferVitagroup agree to put all my contributions to SORMAS-Docker under GPLv3 license.

**Comment by vidi42** [comment]
I @vidi42 agree to put all my contributions to SORMAS-Docker under GPLv3 license.

**Review by fhauptmann — APPROVED** [review]

**Comment by hzi-old** [comment]
I agree to the licence

**Comment by fhauptmann** [comment]
I agree to the licence

**Comment by ulf1** [comment]
I @ulf1 agree to put all my contributions to SORMAS-Docker under GPLv3 license

**Comment by robbmue** [comment]
I @robbmue  agree to put all my contributions to SORMAS-Docker under GPLv3 license

**Comment by nliakm** [comment]
I @nliakm agree to put all my contributions to SORMAS-Docker under GPLv3 license.

**Comment by TomHutter** [comment]
I @TomHutter agree to put all my contributions to SORMAS-Docker under GPLv3 license.

**Comment by asohh** [comment]
I @asohh  agree to put all my contributions to SORMAS-Docker under GPLv3 license.

**Comment by kadeng** [comment]
I @kadeng agree to put all my contributions to SORMAS-Docker under GPLv3 license.

**Comment by sabpet** [comment]
I @sabpet agree to put all my contributions to SORMAS-Docker under GPLv3 license.

**Pull request merged**
