### PR TITLE
322 update payara

### LINKED ISSUE #322: Update to Payara 5.2021.10
Counterpart of https://github.com/hzi-braunschweig/SORMAS-Project/issues/4601

### PR DESCRIPTION
**Pull request by vidi42**
Fixes #322 

Has to be merged at the same time with https://github.com/hzi-braunschweig/SORMAS-Project/issues/4601

### CODE REVIEW

**Comment by nliakm** [comment]
Note: also make sure to adjust the jenkins jobs refering to the deleted dockerfiles

**Comment by StefanKock** [comment]
> Note: also make sure to adjust the jenkins jobs refering to the deleted dockerfiles

@nliakm I don't know what/where to change anything concerning dockerfiles. Would anything break if we merge it like this?

**Comment by nliakm** [comment]
@StefanKock I asked @asohh about the planned changes. If there is no objection, I will merge this PR.

**Comment by StefanKock** [comment]
> @StefanKock I asked @asohh about the planned changes. If there is no objection, I will merge this PR.

> Has to be merged at the same time with [hzi-braunschweig/SORMAS-Project#4601](https://github.com/hzi-braunschweig/SORMAS-Project/issues/4601)

@nliakm better not merge it yourself, let me do it in sync with SORMAS-Project otherwise SORMAS-Docker is broken!

**Comment by nliakm** [comment]
@StefanKock Jenkins job that has to be adjusted "Daily Build Container New jdk"

**Pull request merged**
