### PR TITLE
#320 Update the Keycloak docker image to 16.1.0

### LINKED ISSUE #320: Update to Keycloak 16
Counterpart of https://github.com/hzi-braunschweig/SORMAS-Project/issues/5901

### PR DESCRIPTION
**Pull request by vidi42**
Fixes #320 

Has to be merged at the same time with https://github.com/hzi-braunschweig/SORMAS-Project/issues/5901

### CODE REVIEW

**Comment by nliakm** [comment]
@vidi42 All fine. Just let me know when to merge it.

**Review by nliakm — APPROVED** [review]

**Comment by JonasCir** [comment]
@nliakm Did you spin up to containers to test?
I ask b/c I encounter two issues while running `docker compose -f docker-compose-keycloak.yml up  -d` in this branch:

1. A general problem is that the `sormas` container cannot resolve `sormas-docker-test.com`. Quick fix for this is to inspect the `apache2` container and add the found ip in the sormas container's `/etc/hosts` file.
2. I login to keyloak, create a new user and assign it the "USER" role. When I navigate to SORMAS, I get the landing page, I enter my credentials, click on login (I'll receive the cookies), however, SORMAS shows me 403 Forbidden, but without logging any error.

Can you guys take a look?

**Comment by vidi42** [comment]
@JonasCir 
What I usually do when running the SORMAS-Docker locally is to add 
```
    extra_hosts:
      - "sormas-docker-test.com:${my_local_ip_here}"
```
to the sormas service in `docker-compose-keycloak.yml` which ensures the mapping is done correctly for the domain

**Comment by vidi42** [comment]
> @nliakm Did you spin up to containers to test? I ask b/c I encounter two issues while running `docker compose -f docker-compose-keycloak.yml up -d` in this branch:
> 
> 1. A general problem is that the `sormas` container cannot resolve `sormas-docker-test.com`. Quick fix for this is to inspect the `apache2` container and add the found ip in the sormas container's `/etc/hosts` file.
> 2. I login to keyloak, create a new user and assign it the "USER" role. When I navigate to SORMAS, I get the landing page, I enter my credentials, click on login (I'll receive the cookies), however, SORMAS shows me 403 Forbidden, but without logging any error.
> 
> Can you guys take a look?

As for the second step, you need to have the user created in SORMAS as well. It's not enough to have created it in Keycloak.

**Comment by JonasCir** [comment]
Ok that did the trick thanks

**Comment by JonasCir** [comment]
@nliakm ready to merge

**Pull request merged**
